name: Release
on: push

jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - 
        name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          install-deps: true
          setup-python: 'false'
          arch: 'win64_mingw81'
          version: '6.1.0'
          tools: 'tools_openssl_x64'
      - name: 'Run CMake'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=Release'
          cmakeListsTxtPath: '${{ github.workspace }}\CMakeLists.txt'
          buildDirectory: '${{ github.workspace }}\build'
      #- name: Move G++
      #  run: |
      #    get-command g++.exe | % { copy-item -Path $_.Path -Destination D:\a\hydownloader-systray\Qt\6.1.0\mingw81_64\bin}
      -
        name: windeployqt
        run: |
          mkdir '${{ github.workspace }}\release'
          move '${{ github.workspace }}\build\hydownloader-systray.exe' '${{ github.workspace }}\release'
          get-command libgcc_s_seh-1.dll | % { copy-item -Path $_.Path -Destination '${{ github.workspace }}\release'}
          get-command libstdc++-6.dll | % { copy-item -Path $_.Path -Destination '${{ github.workspace }}\release'}
          get-command libwinpthread-1.dll | % { copy-item -Path $_.Path -Destination '${{ github.workspace }}\release'}
          get-command libcrypto-1_1-x64.dll | % { copy-item -Path $_.Path -Destination '${{ github.workspace }}\release'}
          get-command libssl-1_1-x64.dll | % { copy-item -Path $_.Path -Destination '${{ github.workspace }}\release'}
          windeployqt --verbose 2 --release --compiler-runtime '${{ github.workspace }}\release\hydownloader-systray.exe'
      - 
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Extract
          path: '${{ github.workspace }}\release'
          if-no-files-found: error
          retention-days: 2