name: Release
on: push

jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - 
        name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          install-deps: true
          setup-python: 'false'
          arch: 'win64_mingw81'
          version: '6.1.0'
      - name: 'Run CMake'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=Release'
          cmakeListsTxtPath: '${{ github.workspace }}\CMakeLists.txt'
          buildDirectory: '${{ github.workspace }}\build'
      -
        name: windeployqt
        run: windeployqt --compiler-runtime '${{ github.workspace }}\build\hydownloader-systray.exe'
      - 
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Extract
          path: '${{ github.workspace }}\build'
          if-no-files-found: error
          retention-days: 2